#
# Custom status led and "Locate" switch.
#

substitutions:
  status_led_output_platform: esp8266_pwm
  status_led_output_pin: GPIO13
  status_led_output_inverted: "True"
  status_led_switch: no_switch

output:
  - id: status_led
    platform: ${status_led_output_platform}
    pin: ${status_led_output_pin}
    inverted: ${status_led_output_inverted}

light:
  - id: status_light
    platform: monochromatic
    output: status_led
    internal: True
    effects:
      - pulse:
          name: Scan
          transition_length: 200ms
          update_interval: 400ms
      - pulse:
          name: Locate
          transition_length: 1s
          update_interval: 2s

esphome:
  on_loop:
    then:
      - if:
          condition:
            and:
              - not: wifi.connected
              - switch.is_off: scanning
          then:
            - switch.turn_on: scanning

      - if:
          condition:
            and:
              - wifi.connected
              - switch.is_on: scanning
          then:
            - switch.turn_off: scanning

      - if:
          condition:
            and:
            - switch.is_off: scanning
            - switch.is_off: locate
          then:
          - if:
              condition:
                switch.is_on: ${status_led_switch}
              then:
                - if:
                    condition:
                      light.is_off: status_light
                    then:
                      - light.turn_on:
                          id: status_light
                          transition_length: 0s
              else:
                - if:
                    condition:
                      light.is_on: status_light
                    then:
                      - light.turn_off:
                          id: status_light
                          transition_length: 0s

switch:
  - id: no_switch    # Dummy switch to make compiler happy.
    platform: template
    internal: True
    optimistic: True

  - id: scanning
    platform: template
    internal: True
    optimistic: True

    on_turn_on:
      - light.turn_on: 
          id: status_light
          effect: Scan

    on_turn_off:
      - light.turn_off: 
          id: status_light
          transition_length: 0s

  - name: Locate
    id: locate
    platform: template
    icon: mdi:home-search
    optimistic: True

    on_turn_on:
      - light.turn_on: 
          id: status_light
          effect: Locate

    on_turn_off:
      - light.turn_off: 
          id: status_light
          transition_length: 0s
