#
# Device-specific: Sonoff Mini, Sonoff Mini R2 (for lights)
#

substitutions:
  light_restore_mode: ALWAYS_OFF

esp8266:
  board: esp01_1m

output:
  - id: relay
    platform: gpio
    pin: GPIO12

light:
  - name: None    # Uses device friendly name -- https://esphome.io/components/light/index.html#base-light-configuration
    id: light_relay
    platform: binary
    output: relay
    restore_mode: ${light_restore_mode}

binary_sensor:
  - name: Button
    platform: gpio
    pin: 
      number: GPIO0
      inverted: True
    on_click:
      - light.toggle: light_relay

  - name: Switch
    platform: gpio
    pin: GPIO04
    filters:
      - delayed_on_off: 100ms
    on_state:
      - light.toggle: light_relay

packages:
  base: !include
    file: ./.status-led.yaml
