#
# Device-specific: Sonoff Zigbee Bridge PRO
#
# Source: https://github.com/Giancky79/ZB-Bridge-P
#         https://templates.blakadder.com/sonoff_ZBBridge-P.html
#

esp32:
  board: esp32dev
  framework:
    type: arduino

esphome:
  on_boot:
    priority: 800
    then:
      - switch.turn_on: zigbee_rst
      - delay: 15ms
      - switch.turn_off: zigbee_rst
      - delay: 1s
      - light.turn_on: blue
      - delay: 1s
      - rtttl.play: 'long:d=1,o=5,b=100:e6' 

web_server:
  version: 3

logger:
  baud_rate: 0    # Disable

api:
  reboot_timeout: 0s    # Disable

output:
  - id: status_bls
    platform: gpio
    pin: GPIO21    # Green led
    inverted: True    

  - id: rtttl_out 
    platform: ledc
    pin: GPIO4    # Buzzer

light:
  - id: blue
    platform: status_led
    pin: 
      number: GPIO2
      inverted: true
    internal: True
    restore_mode: ALWAYS_OFF

  - id: green
    platform: binary
    output: status_bls
    internal: True
    restore_mode: ALWAYS_OFF

rtttl:
  output: rtttl_out

uart:
  id: uart_bus
  rx_pin: GPIO23
  tx_pin: GPIO19
  baud_rate: 115200  

stream_server:
  port: 6638
  uart_id: uart_bus

external_components:
  - source: github://oxan/esphome-stream-server

binary_sensor:
  - platform: status
    name: Status

  - platform: stream_server
    connected:
      name: Connected

switch:
  - platform: gpio
    id: zigbee_rst
    pin: 15
    name: "Zigbee RST"
    inverted: True
    internal: True
    restore_mode: ALWAYS_OFF

  - platform: gpio
    id: zigbee_bsl
    pin: 22
    name: "Zigbee BSL"
    inverted: True
    internal: True
    restore_mode: ALWAYS_OFF
