#
# Device-specific: Sonoff Mini, Sonoff Mini R2
#

esp8266:
  board: esp01_1m

switch:
  - name: None    # Uses device friendly name -- https://esphome.io/components/switch/#base-switch-configuration
    id: relay
    platform: gpio
    pin: GPIO12

binary_sensor:
  - name: Button
    platform: gpio
    pin: 
      number: GPIO0
      inverted: True
    on_click:
      - switch.toggle: relay

  - name: Switch
    platform: gpio
    pin: GPIO04
    filters:
      - delayed_on_off: 100ms
    on_state:
      - switch.toggle: relay

packages:
  base: !include
    file: ./.status-led.yaml
