#
# Device-specific: Sonoff Mini, Sonoff Mini R2 (for remote control)
#
# Should extend 'switch_sensor.on_state' in main yaml file calling the desired action. E.g.
#
# binary_sensor:
#   - id: !extend switch_sensor
#     on_state:
#       - http_request.post: http://remote-bulb/light/generic_bulb/toggle
#

esp8266:
  board: esp01_1m

switch:
  - name: Relay
    id: relay
    platform: gpio
    pin: GPIO12
    restore_mode: ALWAYS_ON

http_request:
  id: http_client
  esp8266_disable_ssl_support: True
  timeout: 2s

binary_sensor:
  - name: Button
    platform: gpio
    pin: 
      number: GPIO0
      inverted: True
    on_click:
      - switch.toggle: relay

  - name: None    # Uses device friendly name -- https://esphome.io/components/switch/#base-switch-configuration
    id: switch_sensor
    platform: gpio
    pin: GPIO04
    filters:
      - delayed_on_off: 100ms
#   on_state:

packages:
  base: !include
    file: ./.status-led.yaml
